Feature/full website
Ayokunnumi1/math-magician pull request #5
Opened 2023-09-20 19:27 UTC by Ayokunnumi1

These are the functionalities implemented in this branch;
- A website consisting of 3 pages: Home, Calculator, and Quote.
- For every page, I created a route,
- Use React Router to make the routes work.

2023-09-20 21:06 UTC, Munsa1 requested changes
Hi @Ayokunnumi1, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! You have done great work and please do not take these suggestions as a hindrance to your progress but rather as a nudge to perfect your work even more!

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Unique UI Design :heavy_check_mark: 
Use Of React Router :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._
### Due to insufficient files changed I will leave some comments here

- [ ] Kindly fix the link to your MIT license, it should link to the LICENSE.md agreement file and not to your GitHub profile
![image](https://github.com/Ayokunnumi1/math-magician/assets/81932478/7110bafe-a256-44ee-9faf-8af06a999dd0)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 21:06 UTC, Munsa1 commented on src/components/Home.js
> +};
- [ ] Great job implementing the pages of the app using React Router. A small change is required to improve your design. Kindly note that we need to follow the given wireframe for the general layout of our pages.

Your design
![image](https://github.com/Ayokunnumi1/math-magician/assets/81932478/4f0ccebb-04ad-4cdd-9f98-fb1c590dc685)

Given frame
![image](https://github.com/Ayokunnumi1/math-magician/assets/81932478/50129d9b-e802-4966-bfb5-2f5a4f2ab99c)

- Align your heading and paragraph to the left as is in the given frame and not in the center as you have done
- Also the links from left to right should be `Home Calculator Quote` and not `Home Quote Calculator`. This minor change will definitely improve user experience and accessibility

2023-09-20 21:06 UTC, Munsa1 commented on src/components/calculator.js
>  import calculate from '../Logic/calculate';
- [ ] Also it would be nice if we followed the given layout for the calculator page by aligning our calculator to the right as is in the given wireframe and not in the middle as you have done.

Your design
![image](https://github.com/Ayokunnumi1/math-magician/assets/81932478/4f78aa1f-b6f9-4b87-8917-bdeef68d3074)

Given frame
![image](https://github.com/Ayokunnumi1/math-magician/assets/81932478/ad5feff6-406e-479d-ae12-d01e0235efb9)

2023-09-20 21:06 UTC, Munsa1 commented on src/components/Home.js
> +/* eslint-disable arrow-body-style */
- [ ] Kindly do not use disable linters as they help us to write clean industry-standard code.

2023-09-21 04:54 UTC, Shedrack-Sunday approved these changes
Hi @Ayokunnumi1 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organization ✔️
- [x] Nice use of React features ✔️ 
- [x] Excellent use of React✔️ 
- [x] Kudus on meeting the requirements as  required  ✔️


Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-09-21 09:48 UTC, merged